name: Build Docker and publish

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t rbernalber/calmayourdrama.projects:latest
      - name: push image to docker hub
        run: docker push rbernalber/calmayourdrama.projects:latest
